# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "ahci" "vmw_pvscsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@var" ];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@cache" ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-uuid/bb79bfcf-d8c8-4ff4-a09b-7124cc0fc0b0";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8361-56E4";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens192.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
